services:
  - type: web
    name: curso-mrs-certificacao
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
    domains:
      - curso-mrs.onrender.com 